### ISSUE TITLE
Import `ontogpt` and run it through this project

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/automaxo#3]
OntoGPT processing could be handled through this project, too - just add it to the dependencies and import:
```python
from ontogpt.engines.spires_engine import SPIRESEngine
```
A more hard-coded version of the `extract` command used in the OntoGPT CLI would get it done and would allow any project-specific preprocessing to be easily added to this project.

**Comment by pnrobinson** [comment]
@caufieldjh  -- is this issue still active or can we close?
