### ISSUE TITLE
Relax search filter (or provide option to do so)

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/automaxo#4]
In the document retrieval functions:
https://github.com/monarch-initiative/automaxo/blob/d931d9c9ac06bae8c36c9bf113a5347b5804fe7e/scripts/retrive_pmids.py#L35-L43

The `search_term` is hardcoded to search on title or abstract, which is great if you're looking for specific disease names.
If you are trying to retrieve a specific document or set of documents, this doesn't work as well since the PMID is found elsewhere in the document metadata.

One solution would be to have the function default to adding `[Title/Abstract]` to the search string like it currently does,
but provide an additional argument like `raw` to allow passing a search string without that filter.

**Comment by pnrobinson** [comment]
@caufieldjh @enockniyonkuru  was this issue resolved?

**Comment by enockniyonkuru** [comment]
Yes the issue was resolved!
